### PR TITLE
add `setDateTime` parameter for `DriverJdbcType[DateTime]`

### PR DESCRIPTION
**Pull request by xuwei-k**
I think #30 is **NOT** right way in most cases.
But I have not change the default behavior directly for keep compatibility.

### CODE REVIEW

**Comment by tototoshi** [comment]
I still don't understand why the current implementation is not correct.

Can you please explain the correct behavior you expect? Or I would like some test code. Also, can you tell me which database you are using?

**Comment by y-yu** [comment]
I supposed something wrong and tried this test: https://github.com/tototoshi/slick-joda-mapper/compare/master...y-yu:slick-joda-mapper:add-utc-zoned-test 👀 

```
[info] MySQLJodaSupportSpec:
[info] JodaSupport
[info] - should enable us to use joda-time with slick
[info] - should enable us to use joda-time with string interpolation API
[info] - should be the same in/out joda-time which is not the same timezone against the global setting *** FAILED ***
[info]   1354806000000 was not equal to 1354838400000 (JodaSupportSpec.scala:226)
[info] - can be used with comparative operators
[info] - should be able to filter with the specified date
[info] Run completed in 16 seconds, 538 milliseconds.
```

This test is comparison of UTC zoned joda `DateTime` value then save into the table, and that loaded from DB. In SQL `TIMESTAMP` doesn't hold timezone but unix epoch times of those must be the same. So I think the current way is not correct.

`getValue` also should be fixed in addition to @xuwei-k san's fix.
https://github.com/xuwei-k/slick-joda-mapper/compare/setDateTime...y-yu:slick-joda-mapper:setDateTime-and-getDateTime

```diff
    override def getValue(r: ResultSet, idx: Int): DateTime =
-      fromSqlType(r.getTimestamp(idx))
+      fromSqlType(r.getTimestamp(idx, Calendar.getInstance(TimeZone.getTimeZone("UTC"))))
```

I don't understand why `ResultSet#getTimestamp` takes `Calendar` but it works.

**Comment by y-yu** [comment]
Are there any updates? 👀

**Comment by y-yu** [comment]
@tototoshi 👀 :pra

**Comment by tototoshi** [comment]
I had the opportunity to speak with @y-yu directly about this issue some time ago. I really want to solve this problem fundamentally. But if it causes incompatible changes, users may have a new accident.

This library is already not actively developed. And there will be no need for it. A major upgrade to fundamentally solve the problem is overkill. This PR is a workaround, but at least it is safe for current users.

**Pull request merged**
